<!--BOOK_INFORMATION-->
<!--<img align="left" style="padding-right:10px;" src="figures/PDSH-cover-small.png">-->

*[Notas de aula da disciplina de 
Modelagem Matemática](https://github.com/rmsrosa/modelagem_matematica)
do [IM-UFRJ](https://www.im.ufrj.br).*

<!--NAVIGATION-->


<a href="https://colab.research.google.com/github/rmsrosa/modelagem_matematica/blob/master/notebooks/01.02-Reconhecimento_de_Jupyter.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a><br>

[<- O Ambiente computacional](01.01-Ambiente_computacional.ipynb) | [Índice](Indice.ipynb) | [Referências](99.00-Referencias.ipynb) | [Gráficos de funções ->](01.03-Graficos_de_funcoes.ipynb)

---


# Reconhecimento de Jupyter

Vamos começar trabalhando aritmética e álgebra linear, para ilustrar o ambiente Jupyter.

## Aritmética

Na versão 3 do Python, trabalhamos essencialmente com três tipos numéricos: **inteiros**, **pontos flutuantes** e **complexos** (veja em [Built-in Types](https://docs.python.org/3/library/stdtypes.html?highlight=numerics)). Há outros tipos também, como [fractions](https://docs.python.org/3/library/fractions.html#module-fractions) e [decimal](https://docs.python.org/3/library/decimal.html#module-decimal), que evitam, ou reduzem, arredondamentos estranhos, mas a custo de velocidade de processamento. Além disso, pacotes numéricos como `numpy` e `scipy` trabalham seus cálculos numéricos essencialmente em ponto flutuante.

Informações mais detalhadas sobre a implementação dos números de ponto flutuante em sua configuração podem ser obtidas através do comando `float_info` do módulo `sys`:

In [160]:
import sys
sys.float_info

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)

Para visualizar o resultado dos cálculos aritméticos, podemos usar a função `print()`:

In [161]:
print(2 + 3)
print(2.0 + 3.0)
print(1.0 + 2.0j)
print(1j**2)

5
5.0
(1+2j)
(-1+0j)


Observe que, no caso de número complexo, a letra `j` representa $\sqrt{-1}$, com o número complexo sendo identificado automaticamente ao concatenarmos um número com a letra `j`. Observe, de fato, que acima fizemos `2.0j` e `1j`. Se fizermos `1.0 + 2.0*j` e `j**2`, teremos, inicialmente, um erro, pois nesse caso o programa espera que `j` seja uma variável a ser multiplicada por `2.0` ou elevada ao quadrado:

In [3]:
print(1.0 + 2.0**j)
print(j**2)

NameError: name 'j' is not defined

E caso definamos `j` como um número, não obteremos erro, mesmo trabalhando com complexos, apenas uma certa confusão, pois `j` ora pode ser a variável, ora pode ser $\sqrt{-1}$, dependende de como ela aparecer:

In [6]:
j = 1 + 2j
print(1*j)
print(j)
print()
print(2j)
print(2*j)
print()
print(j*j)
print(1j*1j)
print(1j*j)

(1+2j)
(1+2j)

2j
(2+4j)

(-3+4j)
(-1+0j)
(-2+1j)


Em python, tudo o que é definido é considerado um **objeto** e tem um **tipo** específico associado. O **tipo** de cada objeto em python pode ser conferido através da função `type()`. Vejamos:

In [162]:
print(type(2 + 3))
print(type(2.0 + 3.0))
print(type(1.0 + 2.0j))

<class 'int'>
<class 'float'>
<class 'complex'>


O conjunto dos números de ponto flutuante do Python inclui infinito

In [1]:
print(float("inf"))
print(type(float("inf")))

inf
<class 'float'>


`inf` é útil em cálculos simbólicos, na designação dos limites do intervalo de definição de uma função ou de intervalos de otimização para variáveis, por exemplo. Também podemos fazer *aritmética estendida*, com infinito:

In [19]:
inf = float("inf")
print(inf + 1)
print(1/inf)
print(-inf + 10)
print(inf + inf)

inf
0.0
-inf
inf


Mas, obviamente, não podemos somar $-\infty$ com $\infty$:

In [20]:
print(inf - inf)

nan


`nan` significa *not a number*. Curiosamente, em python, `nan` é um `float`. Verifique.

Mas qualquer operação aritmética que fizermos com `nan` nos retornará `nan`. Tente!

## Imprimindo textos e números

Como visto acima, números podem ser visualizado pela função `print()`. Textos, também, obviamente. Tecnicamente, isso é possível pois ambos são **objetos** contendo o método `__print__()`, que informa como o seu conteúdo deve ser "impresso". 

Textos e números podem ser combinados de diversas maneiras. E podem ser devidamente formatados, também. Vejamos alguns exemplos:

In [163]:
print('O valor da soma é', 2.0 + 3)
print(f'O valor da soma é {2.0 + 3}')
a1, a2 = 2.0, 3
print(f'O valor da soma entre {a1} e {a2} é {a1+a2}')
print(f'{a1} + {a2} = {a1 + a2}')
print()
print('Um terço é', 1/3)
print(round(100/3)/100)
print('{:.2f}'.format(1/3))
print(f'{1/3:.2f}')

O valor da soma é 5.0
O valor da soma é 5.0
O valor da soma entre 2.0 e 3 é 5.0
2.0 + 3 = 5.0

Um terço é 0.3333333333333333
0.33
0.33
0.33


In [3]:
# Este código exibe o quadrado dos inteiros entre 0 e 9
for i in range(10):
    print(f'{i}\N{SUPERSCRIPT TWO} = {i*i}')

0² = 0
1² = 1
2² = 4
3² = 9
4² = 16
5² = 25
6² = 36
7² = 49
8² = 64
9² = 81


As formatações acima que começam com `f{` geram *strings* chamadas de *f-strings*. Elas foram introduzidas na versão 3.6 do python, pela [PEP-0498](https://www.python.org/dev/peps/pep-0498/). São bastante flexíveis e práticas e são as nossas favoritas aqui. Veja mais sobre *f-strings* em [Python 3: An Intro to f-strings](https://www.blog.pythonlibrary.org/2018/03/13/python-3-an-intro-to-f-strings/) e [Python 3's f-Strings: An Improved String Formatting Syntax (Guide)](https://realpython.com/python-f-strings/).

## Álgebra Linear

O pacote [NumPy](http://www.numpy.org/) é fundamental para computação científica em python. É o pacote natural para Álgebra Linear Computacional. Vários outros pacotes são baseados nele.

Com o `numpy`, podemos definir vetores, matrizes e fazer operações com esses objetos. Vejamos alguns exemplos. Para começar, é preciso importar o `numpy`. É comum abreviar o `numpy` como `np`, no momento da importação. Isso é feito da seguinte forma:

In [50]:
import numpy as np

### Vetores

Agora, definimos alguns vetores e fazemos algumas operações com eles. Vetores (assim como matrizes) são exemplos de *arrays*. No `numpy`, *arrays* são do tipo **ndarray**. O construtor básico de *arrays* no `numpy` é a função `numpy.array()`.

In [165]:
# Vetores em duas e três dimensões:
u1 = np.array([1,2])
u2 = np.array([2,1])
e1 = np.array([1,0,0])
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])
v = np.array([2,1,3])
print(f'u1 = {u1}; u2 = {u2}.\n')
print(f'e1 = {e1}; e2 = {e2}; e3 = {e3}.\n')
print(f'v = {v}.\n')
print(f'O tipo do vetor {v} é {type(v)}')

u1 = [1 2]; u2 = [2 1].

e1 = [1 0 0]; e2 = [0 1 0]; e3 = [0 0 1].

v = [2 1 3].

O tipo do vetor [2 1 3] é <class 'numpy.ndarray'>


O produto escalar entre vetores usa o operador `numpy.dot()` (ou `numpy.vdot()` no caso de vetores complexos):

In [166]:
print(f'O produto escalar entre os vetores {u1} e {u2} é {np.dot(u1, u2)}.\n')

print(f'O produto escalar entre os vetores {v} e [-1,3,2] é {np.dot(v, np.array([-1,3,2]))}.\n')


O produto escalar entre os vetores [1 2] e [2 1] é 4.

O produto escalar entre os vetores [2 1 3] e [-1,3,2] é 7.



### Operações matriciais

In [168]:
mat = np.array([[1.0, 2.0], [3.0, 4.0]])
print('Matriz inicial:\n', mat, '\n')

print('Transposta da matriz:\n',mat.transpose(), '\n')

print('Traço:', np.trace(mat), '\n')

print('Determinante (via decomposição LU):', np.linalg.det(mat), '\n')

print('Inversa:\n', np.linalg.inv(mat), '\n')

print('Autovalores:', np.linalg.eigvals(mat), '\n')

print('Multiplicação entre a matriz e sua inversa:\n', mat @ np.linalg.inv(mat), '\n')

# Formatando para melhor exibição e desprezando erros de ponto flutuante
with np.printoptions(precision=3, suppress=True):
    print('Multiplicação entre a matriz e sua inversa com formatação:\n', mat @ np.linalg.inv(mat), '\n')

print('Matriz homotetia:\n', 3 * np.eye(2), '\n')


mat_rot = np.array([[0.0, -1.0], [1.0, 0.0]])
print('Matriz rotação:\n', mat_rot, '\n')

print('Multiplicação da matriz inicial com a de rotação:\n', mat_rot @ mat, '\n')

print('Multiplicação da matriz rotação com a matriz inicial:\n', mat @ mat_rot, '\n')

Matriz inicial:
 [[1. 2.]
 [3. 4.]] 

Transposta da matriz:
 [[1. 3.]
 [2. 4.]] 

Traço: 5.0 

Determinante (via decomposição LU): -2.0000000000000004 

Inversa:
 [[-2.   1. ]
 [ 1.5 -0.5]] 

Autovalores: [-0.37228132  5.37228132] 

Multiplicação entre a matriz e sua inversa:
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]] 

Multiplicação entre a matriz e sua inversa com formatação:
 [[1. 0.]
 [0. 1.]] 

Matriz homotetia:
 [[3. 0.]
 [0. 3.]] 

Matriz rotação:
 [[ 0. -1.]
 [ 1.  0.]] 

Multiplicação da matriz inicial com a de rotação:
 [[-3. -4.]
 [ 1.  2.]] 

Multiplicação da matriz rotação com a matriz inicial:
 [[ 2. -1.]
 [ 4. -3.]] 



### Resolução de sistemas

Resolvendo o sistema
$$ \begin{cases}
  x + y = 1, \\
  x - 2y = 3.
\end{cases}
$$

In [11]:
mat = np.array([[1.0, 1.0], [1.0, -2.0]])
b = np.array([[1],[3]])
x = np.linalg.solve(mat,b)
print('A solução do sistema é\n', x)

A solução do sistema é
 [[ 1.66666667]
 [-0.66666667]]


### Mais informações

Veja mais detalhes em
- [NumPy User Guide](https://docs.scipy.org/doc/numpy/user/index.html#numpy-user-guide)
- [Quickstart tutorial (de Numpy)](https://docs.scipy.org/doc/numpy/user/quickstart.html)
- [Linear algebra (módulo do numpy)](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
- [Documentação (Numpy e Scipy)](https://docs.scipy.org/doc/)

## Exercícios

1. Ache a projeção ortogonal do vetor $\vec{v} = (0.23, 5.41)$ na reta $y=x/2$.

1. Ache a distância entre o ponto $P = (0.23, 5.41)$ e a reta $y=x/2$.

1. Encontre $A^{21}$, onde $A$ é a matriz 
$$
  A = \left[
      \begin{matrix}
        1 & -1 & 1 & -1 \\
        0 & -1 & 1 & -1 \\
        -1 & 1 & 0 & 1 \\
        1 & 0 & -1 & 1
      \end{matrix}
    \right].
$$

1. Ache os autovalores e autovetores da matriz $A$ anterior.

1. Determine a matriz de rotação, no plano, de $\pi/5$ graus radianos, no sentido trigonométrico.

1. Determine a matriz de projeção, em $xyz$, no subespaço dado por $z = 2x - y$.

1. Resolva o sistema linear
$$ \begin{cases}
  x + 2y + 5z - 4u + 3v + 2w = 1, \\
  x - 4z + 2w = 3, \\
  2x - y + z + 3u - v + w = 0, \\
  x + u - w = 1, \\
  z - u + v - w = -1, \\
  y - z + 3u - 10v - w = 7.
\end{cases}
$$

1. Resolva o sistema linear
$$ \begin{cases}
  x + 2y + 5z - 4u + 3v + 2w = 1, \\
  x - 4z + 2w = 3, \\
  2x - y + z + 3u - v + w = 0, \\
  x + u - w = 1, \\
  z - u + v - w = -1.
\end{cases}
$$

<!--NAVIGATION-->

---
[<- O Ambiente computacional](01.01-Ambiente_computacional.ipynb) | [Índice](Indice.ipynb) | [Referências](99.00-Referencias.ipynb) | [Gráficos de funções ->](01.03-Graficos_de_funcoes.ipynb)

<a href="https://colab.research.google.com/github/rmsrosa/modelagem_matematica/blob/master/notebooks/01.02-Reconhecimento_de_Jupyter.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a><br>
